EMAIL =''
PASSWORD=''
PUBLIC_KEY='6LcTmMYUAAAAAKukx7oF31YJKf8MDwiOHaync9o-'
PRIVATE_KEY='6LcTmMYUAAAAAEhPtyp0JBLpMsMnaT4MUaALk5b_'

# LOCALHOST_PUBLIC_KEY="6LeZo8YUAAAAAKn6yNzTyhdmBW6XKcaGCg0ZSwxA"
# LOCALHOST_PRIVATE_KEY="6LeZo8YUAAAAAEr89N8b1xCo8RiRkI028oVlgiEM"
