# Generated by Django 2.1 on 2019-08-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='SIG',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
