# Generated by Django 2.1 on 2019-06-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Member'), (3, 'Candidate')], default=0),
        ),
    ]
