# Generated by Django 2.1 on 2019-06-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190626_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='SIG',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
