# Generated by Django 2.1 on 2019-08-02 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190802_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundOneSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
        migrations.RemoveField(
            model_name='roundoneentry',
            name='user',
        ),
        migrations.DeleteModel(
            name='RoundOneEntry',
        ),
    ]
