# Generated by Django 2.1 on 2019-07-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_sig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('RE', 'Resume Evaluation Pending'), ('WR', 'Written Round'), ('TE', 'Technical'), ('HR', 'HR')], max_length=2),
        ),
    ]
