# Generated by Django 2.1 on 2019-08-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190802_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundonesubmission',
            name='name',
            field=models.CharField(default='NONAME', max_length=20),
        ),
    ]
