# Generated by Django 2.1 on 2019-08-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190802_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roundonesubmission',
            name='name',
        ),
        migrations.AddField(
            model_name='roundonesubmission',
            name='ans1',
            field=models.TextField(default='NONAME'),
        ),
        migrations.AddField(
            model_name='roundonesubmission',
            name='ans2',
            field=models.TextField(default='NONAME'),
        ),
        migrations.AddField(
            model_name='roundonesubmission',
            name='ans3',
            field=models.TextField(default='NONAME'),
        ),
        migrations.AddField(
            model_name='roundonesubmission',
            name='ans4',
            field=models.TextField(default='NONAME'),
        ),
        migrations.AddField(
            model_name='roundonesubmission',
            name='ans5',
            field=models.TextField(default='NONAME'),
        ),
        migrations.AddField(
            model_name='roundonesubmission',
            name='essayans',
            field=models.TextField(default='NONAME'),
        ),
        migrations.AddField(
            model_name='roundonesubmission',
            name='rollno',
            field=models.CharField(default='NONAME', max_length=10),
        ),
    ]
