# Generated by Django 2.1 on 2019-08-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190802_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundonesubmission',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
