# Generated by Django 2.1 on 2019-08-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190802_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundonesubmission',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
