# Generated by Django 2.1 on 2019-08-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_account_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('RE', 'Application Accepted'), ('WR', 'Written Round'), ('TE', 'Technical'), ('HR', 'HR'), ('SL', 'Selected')], max_length=2),
        ),
    ]
