# Generated by Django 2.1 on 2019-08-21 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_activationrecord'),
        ('accounts', '0013_auto_20190820_2356'),
    ]

    operations = [
    ]
