# Generated by Django 2.2.13 on 2020-08-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_basicresponses'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='esc_counter',
            field=models.IntegerField(default=0),
        ),
    ]
