# Generated by Django 2.2.13 on 2020-08-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_escapecounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='escapecounter',
            name='fullscreen',
            field=models.BooleanField(default=False),
        ),
    ]
