# Generated by Django 2.2.13 on 2020-09-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_escapecounter_fullscreen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('RE', 'Application Accepted'), ('WR', 'Written Round'), ('TE', 'Technical'), ('HR', 'HR'), ('H2', 'HR2'), ('SL', 'Selected')], max_length=2),
        ),
    ]
