# Generated by Django 2.2.13 on 2020-09-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200901_1526'),
        ('accounts', '0019_auto_20200901_1524'),
    ]

    operations = [
    ]
