# Generated by Django 2.2.13 on 2021-05-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_merge_20200907_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('RE', 'Application Accepted'), ('WR', 'Written Round'), ('TE', 'Technical'), ('HR', 'HR'), ('H2', 'HR2'), ('SL', 'Selected'), ('RJ', 'Rejected')], max_length=2),
        ),
    ]
