# Generated by Django 2.2.13 on 2021-09-15 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20210505_1021'),
        ('accounts', '0021_auto_20210503_2126'),
    ]

    operations = [
    ]
