# Generated by Django 2.2.13 on 2021-10-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20210922_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('RE', 'Application Accepted'), ('WR', 'Written Round'), ('AS', 'Assignment'), ('TE', 'Technical'), ('HR', 'HR'), ('H2', 'HR2'), ('SL', 'Selected'), ('RJ', 'Rejected'), ('NS', 'Not Selected')], max_length=2),
        ),
    ]
